export const CardsData = [
    {
        name: "react-resume",
        href: 'https://github.com/SwiftOVATE/react-resume/',
        description: 'Build your own resume using React',
        image: 'https://repository-images.githubusercontent.com/586749730/ca90bb68-b35c-45b9-8d88-65e3d989d550',
        tag: 'Portfolio',
        tagcolor: 'bg-pink-800',
    },
    {
        name: "react-portfolio",
        href: 'https://github.com/SwiftOVATE/react-portfolio/',
        description: 'Build your own portfolio using React',
        image: 'https://repository-images.githubusercontent.com/586749730/ca90bb68-b35c-45b9-8d88-65e3d989d550',
        tag: 'Portfolio',
        tagcolor: 'bg-pink-800',
    },
    {
        name: "github-portfolio",
        href: 'https://swiftovate.github.io/github-portfolio/',
        description: 'Build your own portfolio using GitHub API',
        image: 'https://repository-images.githubusercontent.com/589303939/2f8cca5f-d198-4e04-9534-27e59593ae68',
        tag: 'Portfolio',
        tagcolor: 'bg-pink-800',
    },
    {
        name: "google-sheets-api",
        href: 'https://swiftovate.github.io/google-sheets-api/',
        description: 'Get boilerplate code for Google Sheets API',
        image: 'https://repository-images.githubusercontent.com/578009726/a7ef191c-f39b-4eac-a073-2ef953673138',
        tag: 'Boilerplate',
        tagcolor: 'bg-sky-800',
    },
    {
        name: "firebase-crud",
        href: 'https://firebase-crud-swiftovate.netlify.app/',
        description: 'Provides code for basic CRUD operations using Firebase',
        image: 'https://repository-images.githubusercontent.com/577332347/8c6d1a38-4a52-4895-8f3c-6d00a856da9e',
        tag: 'Boilerplate',
        tagcolor: 'bg-sky-800',
    },
    {
        name: "node-backend",
        href: 'https://swiftovate.github.io/node-backend/',
        description: 'Provides boilerplate code for a Node.js backend',
        image: 'https://repository-images.githubusercontent.com/573531482/518db2ae-ce84-40a6-9427-0f274d67124f',
        tag: 'Boilerplate',
        tagcolor: 'bg-sky-800',
    },
    {
        name: "whatsapp-url",
        href: 'https://swiftovate.github.io/whatsapp-url/',
        description: 'Provides a simple way to generate a WhatsApp URL',
        image: 'https://repository-images.githubusercontent.com/586739384/6f2256de-734a-428d-ba9d-171a03d7437a',
        tag: 'Url',
        tagcolor: 'bg-emerald-800',
    },
    {
        name: "calendar-link",
        href: 'https://calendar-link-swiftovate.netlify.app/',
        description: 'Provides a simple way to generate a Google Calendar Scheduling link',
        image: 'https://repository-images.githubusercontent.com/561443203/414f0d0b-2650-456b-a07b-f76dd7152731',
        tag: 'Url',
        tagcolor: 'bg-emerald-800',
    },

]