export const PERSONAL_URL = 'https://api.github.com/users/pratikkabade/repos'
export const SWIFTOVATE_URL = 'https://api.github.com/orgs/SwiftOvate/repos'
export const DEVELOPMENTGUIDE_URL = 'https://api.github.com/orgs/DevelopmentGuide/repos'
export const OLD_IMAGE_BASE_URL = 'https://raw.githubusercontent.com/SwiftOVATE/Landing-Page/main/assets/'
export const IMAGE_BASE_URL = 'https://raw.githubusercontent.com/dependabot-pr/Static-Files/main/Assets/images/'